export const origAis = [
    {
      id: 1,
      name: '彩票',
      description: '这是一个进行彩票预测的Ai.',
      auther: '张三',
      likes: 1,
      imageUrl: 'static/gallery/images1.jpg',
      date: '2012-03-04',
      category: 'work',
    },
    {
      id: 2,
      name: '彩票',
      description: '这是一个进行彩票预测的Ai.',
      auther: '张三',
      likes: 1,
      imageUrl: 'static/gallery/images1.jpg',
      date: '2012-03-04',
      category: 'work',
    },
    {
      id: 3,
      name: '彩票',
      description: '这是一个进行彩票预测的Ai.',
      auther: '张三',
      likes: 1,
      imageUrl: 'static/gallery/images1.jpg',
      date: '2012-03-04',
      category: 'work',
    },
    {
      id: 4,
      name: '彩票',
      description: '这是一个进行彩票预测的Ai.',
      auther: '张三',
      likes: 1,
      imageUrl: 'static/gallery/images1.jpg',
      date: '2012-03-04',
      category: 'work',
    },
    {
      id: 5,
      name: '彩票',
      description: '这是一个进行彩票预测的Ai.',
      auther: '张三',
      likes: 1,
      imageUrl: 'static/gallery/images1.jpg',
      date: '2012-03-04',
      category: 'work',
    },
  ];
